### PR TITLE
Fixes issue when right clicking on unpublished nodes

### PR DESCRIPTION
**Pull request by Logie61**
This fixes the problem highlighted in issue #19

### CODE REVIEW

**Review by Philo — CHANGES_REQUESTED** [review]
Thanks for the PR, could you also add the same fix to the media re-publishing section below your current fix?

**Comment by Logie61** [comment]
@Philo Done :)

**Comment by Philo** [comment]
Great thanks, and one final request, could you squash your 2 commits so the pull request is clean.

See [here](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) for info

**Comment by Logie61** [comment]
@Philo I think I've managed to squash things down

**Review by Philo — APPROVED** [review]

**Pull request merged**
